export function GetUserToken(sessionData) {
    sessionData = JSON.parse(localStorage.getItem("authenticated"));

    if (sessionData) {
        if (sessionData.token === null) {
            localStorage.removeItem("authenticated");
            return;
        } 

        const url = `https://localhost:7029/api/Auth/loginWithToken?token=${sessionData.token}`;

        // Return the Promise generated by the fetch operation
        return fetch(url)
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.json();
            })
            .catch(error => {
                console.error('Error:', error);
                localStorage.removeItem("authenticated");
                return;
            });
    } else {
        // Return a rejected Promise if sessionData is not available
        localStorage.removeItem("authenticated");
        return Promise.reject("Session data not found");
    }
}
